/**
 * Offline fallback style: a self-contained basemap drawn from bundled
 * Natural Earth (50m) GeoJSON under ``public/basemap`` (generated by
 * ``frontend/scripts/prepare_basemap.py``). Used when remote vector tiles
 * are unreachable (air-gapped RZDM deployments) and as the default basemap
 * in static-mode builds.
 *
 * Design constraints for true offline use:
 * - No ``glyphs`` URL, so no symbol/text layers. Cities are intentionally
 *   omitted: unlabeled point markers add clutter without information.
 * - No ``http(s)`` URLs anywhere: every source is a relative GeoJSON file
 *   served alongside the app.
 */
import type { StyleSpecification } from 'maplibre-gl'

// Vite injects BASE_URL ('./' for the static build, '/' otherwise). Prefixing
// the bundled basemap paths with it keeps them correct in both modes.
const BASE = import.meta.env.BASE_URL || './'
const dataUrl = (file: string) => `${BASE}basemap/${file}`

export const localStyle: StyleSpecification = {
  version: 8,
  name: 'forecastview-local',
  sources: {
    countries: {
      type: 'geojson',
      data: dataUrl('countries.geojson'),
    },
    states: {
      type: 'geojson',
      data: dataUrl('states.geojson'),
    },
  },
  layers: [
    {
      id: 'ocean-background',
      type: 'background',
      paint: { 'background-color': '#0b1a2b' },
    },
    // Land fill: the country polygons double as coastlines, so no separate
    // land layer is needed. ID deliberately avoids the LayerPanel border
    // patterns so toggling "Country Borders" keeps the land visible.
    {
      id: 'land-fill',
      type: 'fill',
      source: 'countries',
      paint: { 'fill-color': '#16283c' },
    },
    // Country borders — matches the LayerPanel 'admin-0' toggle pattern.
    {
      id: 'countries-admin-0',
      type: 'line',
      source: 'countries',
      paint: { 'line-color': '#3a5a7a', 'line-width': 0.8 },
    },
    // US state borders — matches the LayerPanel 'admin-1' toggle pattern.
    // Only meaningful when zoomed in, so gated with minzoom.
    {
      id: 'states-admin-1',
      type: 'line',
      source: 'states',
      minzoom: 3,
      paint: { 'line-color': '#2f4a63', 'line-width': 0.6 },
    },
  ],
}

export default localStyle
